GooManSa/algorithm-study

- ChangIl/202504/01 PRG 같은 숫자는 싫어.java
- ChangIl/202504/02 PRG 다리를 지나는 트럭.java
- ChangIl/202504/03 PRG 조이스틱.java
- 프로그래머스 [같은 숫자는 싫어](https://school.programmers.co.kr/learn/courses/30/lessons/12906)
💡 아이디어 및 접근 방법
- 연속되는 숫자는 하나만 남기고 전부 제거
- 순차탐색하며 
- 가장 최근에 push된 원소와 push할 원소를 비교하고 같지 않은 경우 스택에 push
- stack top을 비교하고 stack push
- 30분
- 
- O(N)
> [20250411] PRG / lv1 / 같은 숫자는 싫어 / 모창일

- ChangIl/202504/01 PRG 같은 숫자는 싫어.java
- ChangIl/202504/02 PRG 다리를 지나는 트럭.java
-## 📌 문제 제목
- 프로그래머스 [다리를 지나는 트럭](https://school.programmers.co.kr/learn/courses/30/lessons/42583)
💡 아이디어 및 접근 방법
- 제약조건
- bridge_length는 다리가 수용할 수 있는 트럭의 갯수
- 1 time 마다 트럭은 1 length 전진 
- 총 weight 를 넘지 않아야 함
- 
- 접근방법
- 트럭이 다리에 올라가는 순서와 나가는 순서는, FIFO 구조
- 시간 조건, 무게 조건을 만족하지 않는다면 현재 다리의 가장 첫 트럭의 조건을 비교해야함
- 트럭 (무게, 들어온 시간)을 리스트로 큐에서 관리
- 30분
- O(N)
> [20250413] PRG / lv2 / 다리를 지나는 트럭 / 모창일

- jonghwan/202504/02 LTC Binary Tree Inorder Traversal.md
- 문제 링크 : [Binary Tree Inorder](https://leetcode.com/problems/binary-tree-inorder-traversal?envType=problem-list-v2&envId=stack)
💡 아이디어 및 접근 방법
- 트리 문제지만 스택을 활용하여 문제 풀이 접근
- 중위 순회를 이용하여 접근
- 왼쪽 서브 트리 순회
- 현재 노드를 방문
- 오른쪽 서브트리를 순회
- 재귀 호출 없이 트리를 중위 순회 스택은 노드를 왼쪽으로 내려가는 경로로 기억하는데 사용
- 이후에 각 노드를 방문하고 오른쪽 서브트리로 이동하는데 활용
- 30분
- <img width="686" alt="Image" src="https://github.com/user-attachments/assets/35ea7058-5a38-4317-a42a-02ff0e3f158e" />
- O(N)
> [20250411] LTC / Easy / Binary Tree Inorder Traversal / 진종환

- JiEun/202504/04 PRG 구명보트.md
- 프로그래머스 : [구명보트](https://school.programmers.co.kr/learn/courses/30/lessons/42885)
<br>
- 문제의 목표 : 모든 사람을 구출하기 위해 필요한 최소 보트 수 구하기
- 그리디 + 투 포인터
[풀이 방식]
1. people 배열 **오름차순 정렬**
- 현 시전에서 가장 가벼운 사람과 무거운 사람을 구하기 위함
2. **투 포인터 사용**
- leftIdx    : 가장 가벼운 사람 인덱스
- rightIdx. : 가장 무거운 사람 인덱스
- 하나의 보트에 두 사람을 같이 태울 수 있다면, 두 인덱스 모두 이동, 그렇지 않다면 rightIdx만 감소
3. leftIdx가 rightIdx보다 커지는 시점에 로직 종료
<br>
- 50분
<br>
<br>
- **O(n log n)**
-  Arrays.sort() : 평균 O(n log n)
- 투 포인트 탐색  : O(n)
> [20250420] PRG / lv2 / 구명보트 / 이지은

- JeYoun/202504/02 PRG 조이스틱.md
- 플랫폼명 : [프로그래머스 조이스틱] https://school.programmers.co.kr/learn/courses/30/lessons/42860
<br>
- 알파벳 바꾸는 횟수 구하기 (위 아래 이동)
`answer += Math.min( c - 'A' , 'Z' - c + 1);`
- 연속된 A가 끝나는 지점 찾기
```java
int next = i + 1;
while(next < len && nameArr[next] == 65){
next++;
}
```
- 좌우이동 최소 횟수 구하기 (순서대로 가기 vs 뒤로 돌아가기)
```java
move = Math.min(move, i * 2 + (len - next));
move = Math.min(move, (len - next) * 2 + i);
```
<br>
- 2시간
<br>
<br>
- O(N)
> [20250420] PRG/lv2/조이스틱/이제윤

- JeYoun/202504/01 PRG 체육복.md
- JeYoun/202504/02 PRG 조이스틱.md
- [프로그래머스](https://school.programmers.co.kr/learn/courses/30/lessons/42862)
<br>
- 여벌 체육보을 가졌지만 도난당한 사람
```java
for(int i = 0; i<reserve.length; i++){
int it = reserve[i];
if(lostSet.contains(it)){
answer++;
lostSet.remove(it);
reserveSet.remove(it);
}
}
```
<br>
- 2시간
<br>
- 실행 시간 캡쳐
<br>
- O(N)
> [20250420] PRG/lv1/체육복/이제윤

- ChangIl/202504/04 PRG 섬 연결하기.java
- 프로그래머스 : https://school.programmers.co.kr/learn/courses/30/lessons/42861
<br>
- MST 문제
- undirected, weighted edge
- 최소 비용 + 모든 정점 연결 + 사이클 없음
- Prim 알고리즘 적용
- 최대 간선의 갯수 n(n-1)/2
1. 하나의 정점에서 최소 비용의 간선을 선택
2. 방문하지 않은 정점이면 추가
3. 모든 정점을 방문할 때까지 반복
- PriorityQueue 사용
- Node Class 사용, Comparable 인터페이스 구현
<br>
- 1시간
<br>
<br>
- O(E long E)
- O(n^2 log n)
> [20250418] PRG / lv3 / 섬 연결하기 / 모창일

- Jeonghwan/202504/04 PRG 조이스틱.md
- 문제 링크 : [프로그래머스 조이스틱](https://school.programmers.co.kr/learn/courses/30/lessons/42860#)
💡 아이디어 및 접근 방법
- 최대 이동 거리는 문자열의 길이 len
- 완전 탐색을 사용하면  len을 최대로 조건을 걸더라도 경우의 수가 너무 많음
- 그리디하게 풀기 위해서 규칙성을 분석
- 시작점이 없다고 가정할 경우  연속된 'A'가 가장 긴 구간을 피해서 순회하면 됨(해당 시작을 X, 끝을 Y)
- 실제 시작점은 0번째 인덱스이기 때문에 이동거리는 0 -> X, X -> Y 로 가는 거리를 더하여 최소 이동거리를 구할 수 있음
- 90분
- O(N^2)
> [20250415] PRG / lv2 / 조이스틱 / 김정환

- Jeonghwan/202504/05 PRG 큰 수 만들기.md
- 플랫폼명 : [프로그래머스 큰 수 만들기](https://school.programmers.co.kr/learn/courses/30/lessons/42883)
<br>
- 길이가 n인 숫자의 경우의 수 중에서 가장 큰 값을 찾아야함
- 제한 조건
- number는 2자리 이상, 1,000,000자리 이하인 숫자입니다.
- k는 1 이상 number의 자릿수 미만인 자연수입니다.
-> 완전탐색은 최소 N^2, 해당 상황에서는 N!도 예상됨
- 완전탐색을 사용할 수 없고 일정한 규칙이 예상되어 그리디를 사용
- 맨뒤에서 크기 n의 숫자를 만든 뒤, 역순으로 검사하면서 숫자의 맨 앞의 숫자보다 큰 수가 나오면 교체
- 원래 포함되어 있던 교체된 숫자는 다음 자릿수와 다시 검사하여 교체할 수 있으면 교체
<br>
- 30분
<br>
<br>
- O(N)
> [20250421] PRG / lv2 / 큰 수 만들기 / 김정환

- JeYoun/202504/03 BAJ 덩치.md
- JeYoun/202504/03 BAJ 스위치 켜고 끄기.md
- BAJ : [덩치](https://www.acmicpc.net/problem/7568)
<br>
-  덩치가 확실히 비교될 때만 값을 삽입한 후 증가
-  그렇지 않으면 같은 값을 넣어줌
<br>
- 30m
<br>
- 실행 시간 캡쳐
<br>
- O(N)
> 20250428] BAJ/실버5/덩치/이제윤

- Jeonghwan/202504/07 PRG 키패드 누르기.md
- 플랫폼명 : [프로그래머스 키패드 누르기](https://school.programmers.co.kr/learn/courses/30/lessons/67256)
<br>
- 숫자를 구분하여 손을 선택하는 분기
- 터치시에 answer에 추가하는 메소드
- 손가락과 버튼 간 거리 구하는 메소드
- 각각을 구분하여 구현
<br>
- 40분
<br>
<br>
- O(N)
> [20250428] PRG / lv1 / 키패드 누르기 / 김정환

- jonghwan/202504/04  LTc Container With Most Water.md
- LeetCode : https://leetcode.com/problems/container-with-most-water/description/?envType=problem-list-v2&envId=greedy
<br>
- 투 포인터로 접근 왼쪽 포인터 l=0, 오른쪽 포인터 r=n-1
- width = r - l , height = min(height[l], height[r])
- 더 낮은 쪽으로 포인터를 한 칸 안쪽으로 옮김
<br>
- 1시간 15분
<br>
- 
<br>
- O(n)
> [20250427] LTC / Med / Container With Most Water / 진종환

- jonghwan/202504/04  LTc Container With Most Water.md
- jonghwan/202504/05 BAJ 덩치.md
- jonghwan/202504/06 LTC Spiral Matrix II.md
-LeetCode : https://leetcode.com/problems/spiral-matrix-ii/submissions/1619781726/?envType=problem-list-v2&envId=simulation
<br>
- n×n 2차원 배열 초기화
- 4개의 경계 포인터 (top, bottom, left, right) 와 현재 채울 숫자 num = 1 설정
- 위쪽 행 왼→오
- 오른쪽 열 위→아래
- 아래쪽 행 오→왼
- 왼쪽 열 아래→위
<br>
- 30분
<br>
- ![image](https://github.com/user-attachments/assets/252d7d32-2b91-454d-9203-cd725653a16d)
<br>
- O(n²)
> [20250427] LTC / Med / Spiral Matrix 2 / 진종환

- JiEun/202504/05 BAJ 덩치.md
- 백준 : [덩치](https://www.acmicpc.net/problem/7568)
<br>
- **문제 목표**: 몸무게와 키를 기준으로 덩치 등수 구하기
**[풀이 방식] - 완전 탐색**
1. N명의 사람에 대해 몸무게와 키를 입력 받아 2차원 배열에 저장
``` java 
arr[i][0] → 몸무게  
arr[i][1] → 키
```
2. 이중 for 문을 돌면서 i번째 사람과 j( i+1 ~ N-1) 번째 사람을 비교
- `arr[i][0] < arr[j][0] && arr[i][1] < arr[j][1]`(i보다 j 덩치가 클때)이면
→ **answer[i]++**
- 반대로 j보다 i가 덩치 크면
→ **answer[j]++**
3. 출력시에는 answer에 저장된 등수 +1 
- 등수는 1등부터 시작하기 때문
<br>
- 30분
<br>
<br>
<br>
- O(N^2)
- N이 50 이하이기때문에 완탐으로 충분히 해결 가능
> [20250425] BAJ / 실버5 / 덩치 / 이지은

- ChangIl/202504/05 BOJ 덩치.java
- ChangIl/202504/06 PRG 유연근무제.java
- 백준 : https://www.acmicpc.net/problem/7568
<br>
- 덩치가 더 크다고 말할 수 있는 기준 : 키 , 몸무게 둘다 커야 크다고 할 수 있음
- 내 덩치가 현재 어느 순위인가를 알아내는 방법 : 자신보다 더 큰 덩치가 k명인 경우, 내 순위는 k+1 
- k번째 사람에 대해 n명에 대한 완전탐색 -> O(n^2) 이지만 n <= 50
<br>
- 30분
<br>
<br>
- O(n^2)
> [20250427] BAJ / 실버5 / 덩치 / 모창일

- seeun/202504/덩치.md
- seeun/202504/주사위 세개.md
- 백준 : [URL](https://www.acmicpc.net/problem/2480)
<br>
- 입력값(버퍼) -> 문자열 -> 자르고 -> 숫자로 변환
- 주사위 3개밖에 없어서 if-else분으로 분기 처리
<br>
- 30분
<br>
<br>
- O(N)
>  [20250427] BAJ / 실버4 / 주사위 세개 / 최세은

- seeun/202504/덩치.md
- 백준 : [덩치](https://www.acmicpc.net/problem/7568)
<br>
- 방법1 : 입력값을 배열로, 숫자로 변환 후 for문으로 각 인덱스의 값들을 비교해서 클 때만 카운트
- 방법2 : 인덱스가 증가할 때마다 그 전 인덱스와 다시 비교하지 않기 위해 랭킹 배열의 값을 1로 초기화 하고 해당 인덱스의 다음 인덱스와만 비교하도록 하여 한번씩만 비교하게 함
<br>
- 30분
<br>
<br>
- O(N^2)
> [20250427] BAJ / 실버5 / 덩치 / 최세은

- JiEun/202504/06 BAJ ZOAC.md
- 백준 : [ZOAC](https://www.acmicpc.net/problem/16719)
<br>
- 문제 목표: 사전순으로 가장 앞에 오는 문자열을 순서대로 출력
- 가장 앞에 오는 알파벳은 찾은 뒤 추가해나가는 식으로 하려했으나 시간 복잡도가 커질 것으로 예상되어, 가장 긴 문자열부터 시작해  앞에 올 문자열을 찾아가는 방식으로 `문자 제거 방식의 풀이`를 선택
**[문제 풀이]**
- 문자열의 길이만큼 삭제할 문자를 찾는 `find 함수` 호출
- **find 함수**
- 문자열 앞에서부터 비교하며 현재 비교하는 문자가 다음에 오는 문자보다 빠르다면,
해당 인덱스를 삭제 인덱스로 선택 후 종료
- 해당 인덱스를 StringBuilder에서 삭제 후, 정답 배열에 추가
<br>
- 90분
<br>
<br>
<br>
- O(N^2)
- find 실행 횟수 : O(N) 
- find 함수 : O(N)
> [20250428] BAJ / 골드5 / ZOAC / 이지은

- JiEun/202504/07 PRG 타겟 넘버.md
- 프로그래머스 : [타겟 넘버](https://school.programmers.co.kr/learn/courses/30/lessons/43165?language=java)
<br>
- 문제 목표: 모든 숫자를 사용한 결과가 target이 되는 경우의 수를 구함
**[문제 풀이] - DFS**
- 숫자마다 `더하기(+)`, `빼기(-)` 두 가지 선택지가 존재
- 재귀 함수를 통해 더하기와 빼기 경우 각각을 탐색
- depth가 끝까지 도달했을 때, 누적 합이 target이면 경우의 수에 추가
<br>
- 8분
<br>
<br>
<br>
- O(2^N)
- N이 최대 20이라 가능
> [20250429] PRG / lv2 / 타겟 넘버 / 이지은

- ChangIl/202504/08 PRG 게임 맵 최단거리.java
- ChangIl/202505/03 BOJ 두 용액.java
- ChangIl/202505/04 BOJ 최소 스패닝 트리.java
- ChangIl/202505/05 BOJ 네트워크 연결.java
- 프로그래머스 : https://school.programmers.co.kr/learn/courses/30/lessons/1844
<br>
- 목표지점까지 최단거리로 도착해야하는 문제
- 도착할 수 없는 경우 -1 리턴
- depth(레벨별)별로 가장 최단거리부터 탐색하는 bfs 사용
- 방문한 depth를 기록 및 방문여부 파악을 위해 visited[][]배열 사용
- visited[x][y] = 시작점으로부터 (x,y)까지의 최단거리
- Queue : ArrayDeque vs LinkedList
- ArrayDeque는 동적 배열 기반 (null 불가, 메모리와 속도 효율적)
- LinkedList는 양쪽 삽입이 빈번하게 일어난다면 (Deque)
- add와 remove() 는 O(1)
<br>
- 1시간
<br>
<br>
- O(nm) -> O(n^2)
> [20250426] PRG / LV2 / 게임 맵 최단거리 / 모창일

- ChangIl/202505/06 PRG 가장 큰 수.java
- ChangIl/202505/12 BOJ 별자리 만들기.java
- 프로그래머스 : https://school.programmers.co.kr/learn/courses/30/lessons/42746
<br>
- 주어진 수 배열을 재정렬해서, 하나의 수로 나열했을때 가장 큰 수가 되도록 만들어야 함
- 두 수 a,b 를 문자로 a+b, b+a 를 비교했을때 더 큰 경우의 앞에 위치하는 수가 더 큼
- 750 vs 75 : 75075 vs 75750 
- 75 > 750
- 수 배열을 문자열로 전환해서 이어붙이기
- 모든 수가 0이라면, 0000이 아닌 0 (edge case)
- Arrays.sort()는 primitive 타입의 경우에는 quicksort, object 면 timsort? 암튼 최적화 잘 되어있다
- Arrays.sort()의 두번째 인자로 Comparator 구현체 전달해주기
- compare override
- Comparator vs Comparable (functional interface)
- Comparator : 두 객체를 비교
- compareTo(object o1, object o2)
- Comparable : 자기 자신과 매개변수를 비교
- compare(object o1)
<br>
- 30분
<br>
<br>
- O(nlogn)
> [20250521] PRG / LV2 / 가장 큰 수 / 모창일

- JiEun/202505/08 BOJ 좌표 압축.md
- 백준 : [좌표 압축](https://www.acmicpc.net/problem/18870)
<br>
**[문제 풀이]**
1. 좌표를 담은 배열 복사 및 정렬
```java
int [] copy = arr.clone(); //좌표를 담은 배열 복사
Arrays.sort(copy); //복사한 배열 오름차순 정렬
```
2. **HashMap**을 활용해 좌표 압축 실행
- 정렬된 copy 배열을 순회하며, 각 고유한 숫자에 대해 idx 값을 매핑하여 Map<Integer, Integer>에 저장
- 중복된 값은 무시 (containsKey 활용)
- 고유한 값마다 인덱스를 증가시키며 0부터 압축 인덱스를 부여
```java
for(int i = 0; i<N; i++) {
if(!map.containsKey(copy[i])) { //map에 들어가 있지 않은 좌표 값만 계산
map.put(copy[i], idx);
idx++;
}
}
```   
<br>
- 20분
<br>
<br>
O(N log N)
> [20250523] BOJ / 실버2 / 좌표 압축 / 이지은

- Jeonghwan/202505/01 PRG 단어 변환.md
- 플랫폼명 : [프로그래머스 단어 변환](https://school.programmers.co.kr/learn/courses/30/lessons/43163)
<br>
- 단어를 그래프의 노드, 한글자씩 다른 단어끼리 이동 가능한 간선으로 치환해서 풀음
- "최소 몇 개의 단어를 거쳐서"라는 표현을 통해서 최단 거리를 찾는 문제
- 간선간 비용이 동일하고, 최단거리를 찾는 문제는 bfs가 편리하기 때문에 Queue를 사용하여 풀음
<br>
- 40분
<br>
<br>
- O(V+E)
> [20250508] PRG / lv3 / 단어 변환 / 김정환

- ChangIl/202505/12 PRG 정수 삼각형.java
- 프로그래머스 : https://school.programmers.co.kr/learn/courses/30/lessons/43105
<br>
- dp 기초 문제
- 모든 경로에서의 합중 최대값을 구하는 문제.
- triangle[i][j]까지의 최대값은 triangle[i-1][j-1] + triangle[i][j] vs triangle[i-1][j] + triangle[i][j]
- 근데 triangle[i][j+1]을 구할때 triangle[i-1][j]값을 또 사용함
- 현재까지의 최대합을 따로 dp 배열에 저장해놓기
- 양 끝값일때 index 처리만 잘해주기
- 즉 dp[i][j] = triangle[i][j] + max(triangle[i-1][j-1], triangle[i-1][j])
<br>
- 30분
<br>
<br>
- O(n^2)
> [20250606] PRG / LV3 / 정수 삼각형 / 모창일

- JiEun/202506/10 PRO 등굣길.md
- 프로그래머스 : [등굣길](https://school.programmers.co.kr/learn/courses/30/lessons/42898)
<br>
**DP 초기화**
- **dp[i][j]**: (1,1)에서 (i,j)까지 갈 수 있는 경로의 수
- 시작점인 (1,1)은 1로 초기화
```java
dp[1][1] = 1;
```
- puddles에 해당하는 좌표는 -1로 이동 불가 표기
<br>
**DP 계산**
- puddle인 곳(dp[i][j] == -1)은 건너뛴다
- 위쪽이나 왼쪽 방향에서 오는 경로는 더한다
```java
if(dp[i-1][j] > 0) dp[i][j] += dp[i-1][j]; //위쪽에서 오는 경로
if(dp[i][j-1] > 0) dp[i][j] += dp[i][j-1]; //왼쪽에서 오는 경로
```
- 큰 수 방지를 위해 나머지 연산
```java
dp[i][j] %= 1_000_000_007; 
```
<br>
- 30분
<br>
<br>
- O(n * m)
> [20250604] PRO / lv3 / 등굣길 / 이지은

- JiEun/202506/11 BOJ 5972 택배 배송.md
- 백준 : [택배 배송](https://www.acmicpc.net/problem/5972)
<br>
**[문제 풀이]**
1. 1번 헛간부터 시작하며, PriorityQueue를 이용해 가장 비용이 적은 경로부터 탐색
```java
PriorityQueue<Node> que = new PriorityQueue<>(Comparator.comparingInt(o -> o.cost));
que.add(new Node(1, 0));  // 1번 헛간(시작점), 비용 0으로 큐에 추가
dist[1] = 0;   // 1번 헛간까지의 최소 비용은 0으로 초기화
```
2. 큐에서 꺼낸 노드에 대해, 연결된 모든 인접 노드를 확인
```java
while(!que.isEmpty()) {  // 큐에 노드가 남아있는 동안 반복
Node now = que.poll();  // 현재 비용이 가장 적은 노드를 꺼냄
for(Node next : graph[now.node]) {  // 현재 노드에 연결된 모든 인접 노드 탐색
int nextCost = now.cost + next.cost;  // 현재까지 비용 + 간선 비용
//생략...(3번 내용)
}
}
```
3.  현재까지의 최단 경로 + 간선의 비용 < 기존 최단 거리인 경우, 최단 거리를 갱신하고 큐에 다시 추가
``` java
if(dist[next.node] > nextCost) {  // 새로 계산한 비용이 기존 최단거리보다 작으면
dist[next.node] = nextCost;  // 최단 거리 갱신
que.add(new Node(next.node, …
```
> [20250614] BAJ / 골드5 / 택배 배송 / 이지은

- Jeonghwan/202506/02 BAJ 파티.md
- Jeonghwan/202507/01 BAJ 오큰수.md
- JiEun/202506/11 BOJ 5972 택배 배송.md
- jonghwan/202506/03 BAG 단지번호붙이기.md
- 플랫폼명 :https://www.acmicpc.net/problem/2667
<br>
- 입력으로 N과 그다음 N줄의 문자열을 받아 2차원 배열 grid에 저장
- 같은 크기의 불리언 배열 visited를 만들어 모두 false로 초기화
- 이중 for문으로 모든 칸을 순회하며 grid[i][j] === 1 이고 visited[i][j] === false인 새 단지를 발견하면
- DFS를 호출하여 그 단지에 속한 모든 칸을 방문 처리하고 집 개수를 셈 반환된 집 개수를 리스트 counts에 추가
<br>
- 30분
<br>
- 
<br>
- O(N^2)
> [20250625] BAG / Silver1 / 단지번호붙이기/ 진종환

- Jeonghwan/202507/01 BAJ  에디터.md
- 플랫폼명 : [백준 에디터](https://www.acmicpc.net/problem/1406)
<br>
- 문자열을 커서 위치를 기준으로 두개의 스택으로 관리
- 링크드리스트를 사용하면 속도가 더 빠른 듯
<br>
- 30분
<br>
<br>
- O(N)
> [20250704] BAJ / 실버2 / 에디터 / 김정환

- jonghwan/202507/02 BAG 강의실 배정.md
- 플랫폼명 : https://www.acmicpc.net/problem/11000
<br>
- 우선순위큐 유형의 문제이기에 heap 을 사용하여 down-heap 방식으로 swap함
<br>
- 30분
<br>
- 
<br>
- O(n log n)
> [20250705] BAG / GOLD5 / 강의실배정 / 진종환
